const tasks = [
  { id: 1, title: "Design homepage UI", status: "Pending", priority: "High" },
  { id: 2, title: "Fix login bug", status: "In Progress", priority: "High" },
  { id: 3, title: "Write unit tests", status: "Pending", priority: "Medium" },
  { id: 4, title: "Update documentation", status: "Completed", priority: "Low" },
  { id: 5, title: "Implement user signup", status: "In Progress", priority: "High" },
  { id: 6, title: "Optimize database queries", status: "Pending", priority: "Medium" },
  { id: 7, title: "Deploy app to server", status: "Completed", priority: "High" },
  { id: 8, title: "Set up CI/CD pipeline", status: "Pending", priority: "Medium" },
  { id: 9, title: "Create profile page", status: "In Progress", priority: "Low" },
  { id: 10, title: "Add search functionality", status: "Pending", priority: "High" },
  { id: 11, title: "Build notifications system", status: "In Progress", priority: "High" },
  { id: 12, title: "Fix mobile responsiveness", status: "Completed", priority: "Medium" },
  { id: 13, title: "Test payment gateway", status: "Pending", priority: "High" },
  { id: 14, title: "Add dark mode feature", status: "In Progress", priority: "Low" },
  { id: 15, title: "Setup analytics tracking", status: "Completed", priority: "Medium" },
  { id: 16, title: "Improve SEO performance", status: "Pending", priority: "Medium" },
  { id: 17, title: "Refactor dashboard code", status: "In Progress", priority: "Low" },
  { id: 18, title: "Add file upload feature", status: "Pending", priority: "High" },
  { id: 19, title: "Fix password reset issue", status: "Completed", priority: "High" },
  { id: 20, title: "Integrate email service", status: "Pending", priority: "Medium" },
  { id: 21, title: "Create admin panel", status: "In Progress", priority: "High" },
  { id: 22, title: "Add multi-language support", status: "Pending", priority: "Low" },
  { id: 23, title: "Improve accessibility", status: "Completed", priority: "Medium" },
  { id: 24, title: "Develop chat feature", status: "In Progress", priority: "High" },
  { id: 25, title: "Run load testing", status: "Pending", priority: "High" },
];

export default tasks;
